### PR TITLE
local-studio: stop implying grant enforcement, and test the runtime that ships

### PR DESCRIPTION
**Pull request by 0xSero**
Stacked on `codex/litter-local-bridge`. Found while auditing the Local Studio integration end to end from the mobile client (`0xSero/litter#186`) down through this repo into `sybil-solutions/local-studio`.

**+266 / −0 across 4 files.** No behavior change to the shipping runtime.

Grew from 2 files to 4 because adding CI (§3) found that the crate does not build on Linux (§4).

## 1. `kittylitter local-studio revoke` silently no-ops

Full write-up in #31. Short version:

`f443a83` replaced the signed `LocalStudioBridge` with a second `PiBridge`. The new dispatch arm discards the caller identity outright — `crates/alleycat/src/agents.rs`:

```rust
"local-studio" => {
    let _ = authenticated_node;
    let bridge = self.local_studio_bridge.clone()
        .ok_or_else(|| anyhow!("Local Studio runtime is unavailable"))?;
```

and availability became membership-free:

```rust
pub fn local_studio_gateway_available(&self) -> bool {
    self.local_studio_bridge.is_some()
}
```

`cargo check -p alleycat` confirms the capability layer is unreachable:

```
local_studio.rs:93:15:  warning: function `local_studio_agent_info` is never used
local_studio.rs:144:4:  warning: function `authorized_gateway` is never used
local_studio.rs:42:7:   warning: constant `IMPLEMENTED_CAPABILITIES` is never used
local_studio.rs:483:19: warning: struct `LocalStudioBridge` is never constructed
```

`local_studio_agent_info` was the only reader of `GrantStore::effective`.

The store is still written and read faithfully, so the CLI looks healthy — on a live host right now:

```
$ kittylitter local-studio list
8032ef96…  grants=stats.read,sessions.read,agent.turn  expires=2026-07-28T00:00:00+00:00  revoked=no
88f77a2c…  grants=stats.read,sessions.read,agent.turn  expires=2026-07-28T00:00:00+00:00  revoked=no
ea4a6c63…  grants=stats.read,sessions.read,agent.turn  expires=2026-07-28T00:00:00+00:00  revoked=no
```

Those govern nothing. Any holder of the host pair token can `Connect{agent:"local-studio"}` and get the full app-server surface, and the mobile client additionally forces `AskForApproval::Never` + `SandboxMode::DangerFullAccess` for this runtime. A user revoking a lost phone will be told it worked.

**This PR does not decide the architecture.** It makes the CLI honest in the meantime: every `local-studio` subcommand warns on stderr that grants are not enforced and links #31. Structured stdout is unchanged so scripts keep working.

The real fix is one of the two options in #31 — delete Design A (~5,000 lines, removes 37 dead-code warnings) or re-wire the check. That is a call for the repo owner, not something to land silently overnight.

## 2. The runtime that ships had no tests

Roughly 45 of the ~50 Local-Studio tests in this repo exercise the **dead** gateway path. The live path — `local_studio_bridge` construction, the dispatch arm, `bridge-index` isolation, and `LocalStudioLauncher` — had zero direct coverage.

`LocalStudioLauncher` is the decorator that makes this runtime distinct from `pi` at all. Adds three tests:

- agent-role launch replaces the program, **prepends** rather than replaces the original args, and sets `ELECTRON_RUN_AS_NODE`;
- tool-command role keeps its own program and gains no CLI prefix, but still receives `PI_CODING_AGENT_DIR`;
- an explicit `PI_CODING_AGENT_DIR` is never overridden or duplicated.

```
cargo test -p alleycat --lib
test result: ok. 86 passed; 0 failed  (was 83)
```

The mirror-image decorator on the mobile side gets equivalent coverage in `0xSero/litter#188`.

## 3. This repo had no CI at all

There is no `.github/workflows/` here. Nothing has ever been built or tested automatically — including the code that ships inside every `kittylitter` npm release, since `litter` consumes these crates as a git dependency.

Added one. `cargo build --workspace --all-targets` runs unconditionally; the test step excludes whole crates with a stated reason rather than starting a skip list that quietly grows, so new crates are covered automatically and each exclusion is visible debt:

```
cargo test --workspace \
  --exclude alleycat-bridge-conformance \
  --exclude alleycat-acp-bridge \
  --exclude alleycat-opencode-bridge \
  -- --skip posix_resolver_accepts_dev_suffix_versions
```

**626 tests gate.** Turning CI on found **7 pre-existing failures across 4 crates**, each verified failing against a clean checkout of the branch point — catalogued in #33. Clippy is advisory for now because `crates/alleycat` alone emits 37 dead-code warnings, all from the unreachable gateway in §1.

## 4. The crate does not build on Linux

The very first CI run failed to compile:

```
error[E0609]: no field `pid` on type `GatewayMetadata`
  --> crates/alleycat/src/local_studio.rs:233:68
   = note: available fields are: `url`, `secret`, `controller_id`, `issued_at`
```

`GatewayMetadataFile` (the deserialized `litter-bridge.json`) carries `pid`, but the validated `GatewayMetadata` dropped it — while the `#[cfg(target_os = "linux")]` branch of `bundled_pi_runtime` still reads `metadata.pid` to resolve `/proc/<pid>/{exe,cwd}`. That branch is compiled out on macOS, so this has been broken silently.

Pre-existing and unrelated to §1/§2. Fixed by carrying `pid` through, annotated so it adds no dead-code warning on platforms that resolve via the `.app` bundle.

Relevant to release: `dist-workspace.toml` in `litter` ships `aarch64-unknown-linux-gnu` and `x86_64-unknown-linux-gnu` kittylitter artifacts.

I could not verify this locally — `x86_64-unknown-linux-gnu` is not installed and the musl targets cannot build `ring` without a cross C toolchain — so CI is the check.

## Note on the downstream pin

`litter` pins all four alleycat crates to `rev = "ad5dba33089c61cdf6cd42f307fffd6609b4ff1d"` on this branch, which has no PR into `main`. The branch has moved **four** commits past that pin since it was set:

```
ad5dba3 (litter's pin) → 0f78f3b → b313786 → 84cb342
```

So downstream release artifacts depend on unreviewed commits on a mutable feature branch. Worth landing this branch into `main` so `litter` can pin a reviewed commit instead.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by 0xSero** [comment]
## Added CI, and it found things

Pushed `2f2478a`. This repo had **no `.github/workflows/` at all** — nothing here has ever been built or tested automatically, including the code that ships inside every `kittylitter` npm release, since litter consumes these crates as a git dependency.

Turning CI on found **7 failing tests across 4 crates**, plus one suite that cannot run on a hosted runner. Every one verified failing against a clean checkout of the branch point, so none are mine — catalogued in #33.

```
cargo test --workspace --no-fail-fast   →   746 passed, 7 failed
```

- `alleycat-bridge-core` — `codex_resolver::tests::posix_resolver_accepts_dev_suffix_versions`
- `alleycat-acp-bridge` — `test_acp_to_codex_initialize_result`
- `alleycat-opencode-bridge` — 5 across `v2_cross_cwd`, `v3_resume`, `v7_tool_call_surfacing`
- `alleycat-bridge-conformance` — 2 unit-test failures, plus `conformance_acp` which launches a real ACP agent (its 9 siblings are already `#[ignore]`d)

### Shape of the workflow

`cargo build --workspace --all-targets` runs unconditionally, so a compile break anywhere fails CI regardless of the test exclusions.

For tests I excluded whole crates with a stated reason rather than starting a skip list that quietly grows — new crates get covered automatically, and each exclusion is a visible debt to remove:

```
cargo test --workspace \
  --exclude alleycat-bridge-conformance \
  --exclude alleycat-acp-bridge \
  --exclude alleycat-opencode-bridge \
  -- --skip posix_resolver_accepts_dev_suffix_versions
```

**626 passed, 0 failed** locally with that exact command.

Clippy is `continue-on-error` for now, because `crates/alleycat` alone emits 37 dead-code warnings — all from the unreachable Local Studio gateway in #31. Once that is deleted or rewired, clippy can become blocking.

### Same pattern as the mobile side

`0xSero/litter#188` found the mirror image: iOS CI had only ever run `xcodebuild build`, and turning on `test` exposed 9 pre-existing failures caused by non-hermetic tests reading real device state. Both repos had the same gap — builds gated, behaviour never did.

**Comment by 0xSero** [comment]
## CI green on Linux

`6e3ac72` fixed the build; the run is fully green:

| step | result |
|---|---|
| Build (`--workspace --all-targets`) | success |
| Test | **630 passed, 0 failed** |
| Clippy | non-blocking (see below) |

630 on Linux vs 626 locally on macOS — the delta is platform-gated tests, which is itself a small argument for having CI on a second OS.

### One correction

Clippy reported a green tick but actually **failed** — `continue-on-error` makes GitHub record the step as "success" regardless. It found 3 real findings in `alleycat-bridge-core`, on top of the 37 dead-code warnings from the unreachable gateway in #31.

Renamed the step to "Clippy (advisory, non-blocking)" so nobody reads that tick as a clean lint run, and noted that `continue-on-error` should come off once #31 and #33 land. I'd rather the workflow be honest about what it is not checking.
